
# Adapted from demo 1 from dspins github //AB


# -*- coding: utf-8 -*-
"""D_SPIN_example_hsc.ipynb

Automatically generated by Colab.

Original file is located at
	https://colab.research.google.com/drive/1mjJ09_E9kjEYsGCzf10-aZfuOqHUEV5u
"""

import numpy as np
import anndata as ad
import sys
import matplotlib.pyplot as plt
import os
import pandas as pd
import anton_util
from pathlib import Path
import pickle
# input_dir = Path('inputs')
output_dir = Path('outputs')
[d.mkdir(exist_ok = True) for d in (output_dir, )]






### Convenience functions //AB

def printf(obj = ''):
	print(obj, flush = True)

def pickle_object(obj, path):
	import pickle
	with open(path, 'wb') as f:
		pickle.dump(obj, f)

def unpickle_object(path):
	import pickle
	with open(path, 'rb') as f:
		obj = pickle.load(f)
		return(obj)

def log_timestamp(message = ''):
	import datetime
	printf(f'{str(datetime.datetime.now())}: {message}')






"""## Load data"""

# data_folder = 'dspin_demo_1/DSPIN/data/HSC_simulation/'
# cadata = ad.read_h5ad(data_folder + 'hsc_simulation_with_perturbations.h5ad')


nadatas = unpickle_object(output_dir / 'replogle_log-norm_dspin_filters.pkl')


# from IPython import embed; embed(colors = 'Linux')




# """## Visualize simulation of the HSC network with perturbations"""

# gene_list = cadata.var['gene'].values
# num_gene = len(gene_list)
# samp_list = np.unique(cadata.obs['sample_id'])
# aux_ind = [- 1, 0, 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 3, 4, 5, 6, 7, 8, 9]
# samp_name = ['CONTROL'] + [gene + '\nknock-down' for gene in gene_list] + [gene + '\nactivation' for gene in gene_list]
# samp_list_name = [samp_name[aux_ind[ii] + 1] for ii in range(num_gene * 2 + 1)]

# from sklearn.cluster import KMeans

# kmeans_label = KMeans(n_clusters=7, random_state=0, n_init=10).fit_predict(cadata.X)
# cadata.obs['kmeans'] = kmeans_label

# plot_heatmap_sample = samp_list

# sc.set_figure_params(figsize=[1.2, 2.7])
# fig, grid = sc.pl._tools._panel_grid(0.25, 0.1, ncols=8, num_panels=len(plot_heatmap_sample))
# spin_order = np.array([2, 4, 5, 9, 1, 8, 10, 0, 7, 3, 6])

# for ii, samp in enumerate(plot_heatmap_sample):
#     ax = plt.subplot(grid[ii])
#     cur_filt = (cadata.obs['sample_id'] == samp)
#     samp_order = np.argsort(cadata.obs['kmeans'][cur_filt])
#     plt.imshow(cadata.X[cur_filt, :].T[:, samp_order][spin_order, :], cmap='Blues', aspect='auto', interpolation='none', vmin=0, vmax=2.5)
#     plt.xticks([])
#     plt.yticks([])
#     plt.title(samp_list_name[ii], fontsize=12)

# ax = plt.subplot(grid[0])
# plt.yticks(np.arange(cadata.shape[1]), cadata.var['gene'][spin_order], fontsize=10)
# plt.grid()
# # //AB
# plt.savefig(figures_directory / 'perturbed_HSC_network_simulation.svg')









from dspin.dspin import DSPIN










# def get_Y_and_P(adata):
#     ### Get Y and P
#     log_timestamp('get_Y_and_P...')
#     # Construct Y and P
#     gene_names = [elem.split(sep = '_')[1] for elem in adata.obs.index]
#     adata.obs.insert(loc = 0, column = 'gene name', value = gene_names)

#     Y = pd.DataFrame(adata.X)
#     Y.index = adata.obs['gene name']
#     Y.index.name = 'perturbations'
#     Y.columns = adata.var['gene_name']
#     Y.columns.name = 'genes'

#     rows = np.array(Y.index)
#     cols = np.array(Y.columns)
#     M, N = Y.shape
#     P_np = np.zeros(Y.shape)
#     for ii in range(M):
#         for jj in range(N):
#             if rows[ii] == cols[jj]:
#                 P_np[ii, jj] = -3

#     P = pd.DataFrame(P_np)
#     P.index = rows
#     P.index.name = 'perturbations'
#     P.columns = cols
#     P.columns.name = 'genes'
	
#     d = {'Y': Y, 'P': P}

#     log_timestamp('get_Y_and_P done!')
#     return(d)









"""## Initialize D-SPIN object"""





# from ipdb import set_trace; set_trace()

# num_spin = len(cadata.var)

# model = DSPIN(cadata, save_path, num_spin=num_spin)
# model.network_inference(sample_col_name='sample_id', method='maximum_likelihood', params={'lambda_l1_j': 0, 'lambda_l2_h': 0})
# pickle_object(model, output_dir / f'model_demo.pkl')
# # Takes 5-10 min





	# According to preprint, I am supposed to input h priors here,
	# but cannot see how to do it
	# Ah, maybe cur_h. From default params
		# params = {'num_epoch': 200,
		#           'cur_j': np.zeros((num_spin, num_spin)),
		#           'cur_h': np.zeros((num_spin, num_sample)),
		#           ...
	# prior hi* should be = -3

# From default parameters
		# num_spin = self.num_spin
		# raw_data = self._raw_data

		# if self.example_list is not None:
		#     example_list_ind = [list(self._samp_list).index(samp)
		#                         for samp in self.example_list]
		#     self._samp_list = self._samp_list[example_list_ind]
		#     raw_data = raw_data[example_list_ind]
		#     self._raw_data = raw_data

		# num_sample = len(raw_data)
		# params = {'num_epoch': 200,
		#           'cur_j': np.zeros((num_spin, num_spin)),
		#           'cur_h': np.zeros((num_spin, num_sample)),

# In [11]: len(cadata)
# Out[11]: 13000
# In [13]: len(cadata.var)
# Out[13]: 11

# num_spin = len(cadata.var) below
# num_sample = len(raw_data) above
#   If raw_data = cadata, I have the dimensions I need at least
# but what elements are -3?


# num_sample = len(cadata)



for num_tf, nadata in nadatas.items():
	num_spin = len(nadata.var)
	

	# num_sample = len(nadata)
	# cur_h = np.zeros((num_spin, num_sample))
	# In [17]: cur_h.shape
	# Out[17]: (695, 3241)



	# nadata.obs.insert(
	# 	loc = 0, column = 'gene_name', 
	# 	value = [elem.split(sep = '_')[1] for elem in nadata.obs.index])



	# ynp = get_Y_and_P(nadata)
	# P = ynp['P']
	# In [20]: P.shape
	# Out[20]: (3241, 695)

	# cur_h in input parameters could be prior h. 
	# Based on code for default parameter selection.
	# Let's assume that.
	# Prior hi* are supposed to be -3, rest of h 0 per default cur_h
	# cur_h above has dimensions fitting the transpose of P if I
	# got the correct dimensions also from the default parameter setting.
	# So, cur_h should be 3*P.transpose().
	# I changed in get_Y_and_P above, so it assigns -3 instead of -1
	# for knockdowns.
	# So, 
	# cur_h = np.array(P.transpose())
	# Seems this choice of h was wrong, because it crashes.
	# Specifically, raw_data is grouped according the "conditions",
	# that are the same as the number of different perturbations,
	# not the same as the number of different cells, since several
	# cells can have the same perturbation
	# In the code (without indentation):
	# 
	# def compute_gradient(cur_j, cur_h, raw_data, method, train_dat):
	# ..
	# num_spin, num_round = cur_h.shape
	# ..
	# for kk in range(num_round):
	# j_grad, h_grad = pseudol_gradient(
	# cur_j, cur_h[:, kk].reshape(- 1, 1), raw_data[kk], directed=train_dat['directed'])
	#
	# where raw_data[kk] errors.
	#
	# From bioarxiv, hi, i in [1,M], M number of genes.
	# h_fat(n), perturbation condition n, n in [1,N]
	# 
	# So, h should be grouped by perturbation conditions
	# How does it look like exactly? dspin demos doesn't show.
	# It constructs a default h if none supplied. Could look at that.
	# Looked at that, and a bunch of other code by stepping through
	# using the debugger.
	# The default cur_h is just 0s, so only tells dimensions, as above.
	# Confirmed that num_spin, num_round = cur_h.shape
	# = number of genes, number of distinct perturbations.
	# The ordering of cur_h boils down to the ordering of raw_data,
	# to which it must correspond, see above.
	# The structure and order of raw_data is computed in
	# raw_data_corr or raw_data_state depending on method,
	# but in both cases the ordering comes from 
	# np.unique(data.obs[sample_col_name]), where
	# data is self.adata and sample_col_name is the one supplied
	# to the outwards facing function network_inference
	# self.adata is assigned exactly once, and must thus be the
	# adata supplied as argument to the constructor DSPIN below.
	# So, to recreate cur_h in the same way as done internally for input 
	# as a custom input argument,
	perturbation_list = np.unique(nadata.obs['gene_name'])
	rows = nadata.var.gene_name
	cols = perturbation_list
	cur_h = np.zeros((len(rows), len(cols)))
	for ii in range(len(rows)):
		for jj in range(len(cols)):
			if rows[ii] == cols[jj]:
				cur_h[ii, jj] = -3  # -3 from dspin bioarxiv preprint
	# In [32]: cur_h.sum()/3
	# Out[32]: -499.0
	# In [33]: nadata.shape[1]
	# Out[33]: 694
	# In [34]: nadata.shape[0]
	# Out[34]: 3241
	# Reasonable that 499 out of 694 genes have perturbations among
	# the total 3241 cells included


	extra_params = {'cur_h': cur_h}
	# These params according to the dspin bioarxiv
	params={'lambda_l1_j': 5e-3, 'lambda_l2_h': 0.5}
	all_params = {**params, **extra_params}

	# from IPython.core.debugger import set_trace; set_trace()
	# import ipdb; ipdb.set_trace()
	# from IPython import embed; embed(colors = 'Linux')

	save_path = output_dir / f'dspin/TF_{num_tf}'
	if not os.path.exists(save_path):
		os.makedirs(save_path)

	# I will try running the network_inference in Matlab on Octa4.
	# Eris doesn't have Matlab.
	# The Matlab files are available from the dspin github.
	# I need to manually specify the prior h in the matlab code as well,
	# since network_inference(.. run_with_matlab = True) only saves
	# raw_data to disk, which doesn't have all information to recreate
	# a prior h.
	# Googled, and hdf5 seems to be a suitable file format to transfer
	# the data between the languages
	#
	# import h5py
	# with h5py.File(save_path / "cur_h.hdf5", "w") as f:
	#     dset = f.create_dataset("cur_h", data = cur_h)
	# 
	# Nope, that won't work. See comments in train_network.m on 
	# Octa4 for details. Will instead use hdf5storage for this one as well.    
	# import hdf5storage
	# hdf5storage.savemat(
	#     str(save_path / "cur_h.mat"),  # str() since hdf5storage assumes it
	#     {'cur_h': cur_h},  # Seems to need to be a dict
	#     format='7.3', 
	#     # oned_as='column', 
	#     # store_python_metadata=True,
	#     matlab_compatible = True,
	#     )

	# # For fast testing
	# test_params = {'num_epoch': 3}
	# all_params = {**params, **extra_params, **test_params}
	# # Led to crash towards end of inference
	# # There is some strange indexing of different epochs going
	# # on to find the epoch with the smallest error.
	# # It seems that code expects the number of epochs to be
	# # larger than 3, possibly larger than 50.
	# # Now it ended up trying to access epoch -46 as the best result.
	# # Will just run the default epochs and see.
	# # The crash was close to the end, so hopefully no more crashes
	# # after that
	# # Dicks out for Harambe, Send it!


	anton_util.printf()
	anton_util.log_timestamp(f'model_{num_tf} inference...')
	anton_util.printf()

	model = DSPIN(nadata, save_path, num_spin=num_spin)
	model.network_inference(
		sample_col_name='gene_name', 
		method = 'pseudo_likelihood',
		params = all_params,
		# Based on dspin Matlab code, and the demo 2 example, 
		# the dspin Matlab code runs mcmc_maximum_likelihood
		# This one and pseudo likelihood are not compatible data 
		# format wise. See dspin code for creading raw_data, and
		# how it differs depending on the algorithm chosen.
		# method='mcmc_maximum_likelihood',
		# run_with_matlab = True
		)

	anton_util.printf()
	anton_util.log_timestamp(f'model_{num_tf} inference finished')
	anton_util.printf()


	# Caching inferred network //AB
	anton_util.pickle_object(model, output_dir / f'model_{num_tf}.pkl')

	outs = {
		'cur_j': model.network,
		'cur_h': model.responses
		}

	for name, array in outs.items():
		anton_util.pickle_object(array, output_dir / f'{name}_{num_tf}.pkl')











# """## Compare the inferred network with the ground truth"""

# import re

# ref_network = pd.read_csv(data_folder + '/refNetwork.csv')

# gene_list = cadata.var['gene']
# j_mat = np.zeros([len(gene_list), len(gene_list)])

# for row in ref_network.itertuples():
#     gene1 = row.Gene1
#     gene2 = row.Gene2
#     interaction = row.Type
#     if interaction == '+':
#         j_mat[gene_list == gene1, gene_list == gene2] = 1
#     elif interaction == '-':
#         j_mat[gene_list == gene1, gene_list == gene2] = -1

# j_mat[(j_mat == - 1) & (j_mat.T == 1)] = 1
# j_mat += j_mat.T
# j_mat = np.sign(j_mat)

# j_ref = j_mat.copy()

# import networkx as nx
# import matplotlib.patheffects as patheffects

# def plot_jmat_network():

#     self_loops = [(u, v) for u, v in G.edges() if u == v]
#     G.remove_edges_from(self_loops)

#     eposi= [(u, v) for (u,v,d) in G.edges(data=True) if d['weight'] > 0]
#     wposi= np.array([d['weight'] for (u,v,d) in G.edges(data=True) if d['weight'] > 0])

#     enega = [(u,v) for (u,v,d) in G.edges(data=True) if d['weight'] < 0]
#     wnega = np.array([d['weight'] for (u,v,d) in G.edges(data=True) if d['weight'] < 0])

#     col1 = '#f0dab1'
#     # nx.draw_networkx_nodes(G, pos, ax=ax, node_size=61.8 * nodesz, node_color=col1, edgecolors='None')
#     nx.draw_networkx_nodes(G, pos, ax=ax, node_size=61.8 * nodesz, node_color=node_color, edgecolors='k')

#     sig_fun = lambda xx : (1 / (1 + np.exp(- 5 * (xx + cc))))
#     cc = np.max(np.abs(j_mat)) / 10
#     # edges
#     nx.draw_networkx_edges(G, pos, ax=ax, edgelist=eposi, width=linewz * wposi,
#                             edge_color='#3285CC', alpha=sig_fun(wposi))

#     nx.draw_networkx_edges(G, pos, ax=ax, edgelist=enega, width=- linewz * wnega,
#                             edge_color='#E84B23', alpha=sig_fun(- wnega))

#     margin = 0.2
#     plt.margins(x=0.1, y=0.1)

#     ax.set_axis_off()
#     ax.set_aspect('equal')
#     return ax

# sc.set_figure_params(figsize=[3.2, 3])

# nodesz = 2
# linewz = 1.5
# node_color = ['#f0dab1'] * num_spin
# node_label = np.array(list(gene_list[spin_order]))

# fig, grid = sc.pl._tools._panel_grid(0.1, 0.1, ncols=2, num_panels=2)

# G = nx.from_numpy_array(j_ref[spin_order, :][:, spin_order] * 2)
# spin_order = np.array([2, 4, 5, 9, 1, 8, 10, 0, 7, 3, 6])
# pos = nx.circular_layout(G)

# ax = plt.subplot(grid[0])
# ax = plot_jmat_network()

# path_effect = [patheffects.withStroke(linewidth=4, foreground='w')]
# for ii in range(num_spin):
#     text = plt.text(pos[ii][0], pos[ii][1] - 0.15, node_label[ii], fontsize=13, color='k', ha='center', va='center')
#     text.set_path_effects(path_effect)
# ax.set_title('Ground truth')


# ax = plt.subplot(grid[1])
# cur_j_filt = cur_j.copy()
# cur_j_filt[np.abs(cur_j_filt) < np.percentile(np.abs(cur_j_filt), 40)] = 0
# G = nx.from_numpy_array(cur_j_filt[spin_order, :][:, spin_order])
# ax = plot_jmat_network()
# ax.set_title('D-SPIN')

# plt.savefig(figures_directory / 'network_comparison.svg')




# """## Compute accuracy of the inferred network"""

# def precision_recall_curve(j_ref, cur_j):
#     num_spin = j_ref.shape[0]
#     max_k = int(num_spin * (num_spin - 1) / 2)

#     j_ref = np.triu(j_ref, k=1)
#     cur_j = np.maximum(np.abs(cur_j), np.abs(cur_j).T)
#     cur_j = np.triu(cur_j, k=1)

#     # Flatten and sort the upper triangular portions of the matrices
#     ref_indices = np.argsort(np.abs(j_ref), axis=None)[::-1]
#     cur_indices = np.argsort(np.abs(cur_j), axis=None)[::-1]

#     ref_values = np.sort(np.abs(j_ref), axis=None)[::-1]
#     cur_values = np.sort(np.abs(cur_j), axis=None)[::-1]

#     ref_indices = ref_indices[ref_values > 0]
#     cur_indices = cur_indices[cur_values > 0]

#     # Compute whether each inferred edge is in the list by order
#     edge_in_list = np.isin(cur_indices, ref_indices)
#     correct_predictions_cumsum = np.cumsum(edge_in_list)

#     precision_values = correct_predictions_cumsum / np.arange(1, max_k+1)
#     recall_values = correct_predictions_cumsum / len(ref_indices)

#     return precision_values, recall_values

# precision, recall = precision_recall_curve(j_ref, cur_j)
# print('Top 10 accuracy %.2f , Top 15 accuracy %.2f, Top 20 accuracy %.2f' % (precision[9], precision[14], precision[19]))

